name: Generate `docs/requirements.txt`

on:
  push:
    paths:
      - "pyproject.toml"
      - "uv.lock"

jobs:
  generate-requirements:
    name: Generate `docs/requirements.txt` from pyproject.toml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Export requirements.txt
        run: uv export --only-group docs --no-annotate --no-hashes -o docs/requirements.txt
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update docs/requirements.txt
          # Optional glob pattern of files which should be added to the commit
          file_pattern: docs/requirements.txt
          # Optional. Prevents the shell from expanding filenames.
          # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
          disable_globbing: true
